name: "Acceptance - Landing Page Service and Data Cart"
description: "Validate LPS and Data Cart on testdata.nist.gov"
title: "Release [Version] Acceptance Testing: Landing Pages and Data Cart"
labels:
  - acceptance-testing
  - lps
  - data-cart
body:
  - type: markdown
    attributes:
      value: >-
        Be sure to replace [Version] in the title above.  If necessary, update the testing
        platform, and provide any special instructions.  Assign to a developer for
        completion. 

  - type: textarea
    id: instructions
    attributes:
      label: Instructions
      value: >-
        Please test the release candidate running on the platform noted below and confirm
        the assertions listed below; check the box by each assertion when you have
        confirmed compliance.  If you encounter problems, describe them in comments to
        this issue (and @-tag relevent devlopers), and consider creating a sub-issue.
        When all assertions are confirmed and no problems remain open, click the "Testing
        Complete" box and close this issue.


        Note that checking multiple broswers or OS platforms is _not_ required, unless 
        explicitly requested.


        See the [Acceptance Testing page on
        Confluence](https://nistgov.atlassian.net/wiki/spaces/OKB/pages/15959145/Acceptance+Testing)
        for more information.  

  - type: input
    id: platform
    attributes:
      label: Testing Platform
      value: testdata.nist.gov
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## Landing Page Service (LPS)"

  - type: checkboxes
    id: lps_checks
    attributes:
      label: LPS Checklist
      options:
        - label: Overall display features (spacing, colors, content) is correct
        - label: Server-side log (/data/oar/logs/pdr/lps.log) shows no errors when delivering a landing page.
        - label: File listing appears, folders can be opened, entries are clickable, and download icons appear
        - label: Single-file download works (indicating that the distribution service is working) [add example rec. id. suitable for testdata]
        - label: Ensure Access URL display and link properly
        - label: Choose a LP with a custom Home Page; ensure Visit Home Page button appears and works [add example rec. id.]
        - label: Research Topics display properly (including collection-specific topics)
        - label: metadata display can be opened
        - label: citation can be opened
        - label: version history can be opened
        - label: Make sure bulk download page 
        - label: Ensure Release version badge is up to date

  - type: markdown
    attributes:
      value: "## Data Cart"

  - type: checkboxes
    id: cart_checks
    attributes:
      label: Data Cart Checklist
      options:
        - label: Landing page Download-All works (Bundles are automatically set up and ready for download; download works) [add example rec id]
        - label: Icons (particularly download icons) display correctly

  - type: checkboxes
    id: browser
    attributes:
      label: Browser(s) tested on (check all that apply; all not required)
      options:
        - label: Chrome
        - label: Firefox
        - label: Safari
        - label: Edge
        - label: Other
          
  - type: checkboxes
    id: os
    attributes:
      label: OS platform(s) tested on (check all that apply; all not required)
      options:
        - label: Mac
        - label: Linux
        - label: Windows
        - label: Android
        - label: iOS (IPhone/IPad)
        - label: Other
          
  - type: checkboxes
    id: completion
    attributes:
      label: Testing Completed
      options:
        - label: all acceptance tests completed with no issues found


