name: "Deployment - Post-production Deployment"
description: "Post-production deployment checklist"
title: "[Deployment][Post-Production] "
labels:
  - deployment
  - post-production
body:
  - type: markdown
    attributes:
      value: |
        This checklist can be handled by the deployment manager.

  - type: input
    id: environment
    attributes:
      label: Environment
      placeholder: production
    validations:
      required: true

  - type: input
    id: deployment_manager
    attributes:
      label: Deployment manager
      required: true

  - type: checkboxes
    id: deploy_checks
    attributes:
      label: Deployment Checklist
      options:
        - label: Ensure current-oar-docker link points to the newly deployed oar-docker folder
        - label: Load the SDP home page and ensure recent publications are being displayed (indicating that the RMM is working)
        - label: Click on a landing page to ensure landing pages are displaying properly (and in a timely manner)
        - label: Click on a collection page and ensure that it displays correctly
        - label: Confirm that at least one of the fixes or features introduced as part of this release is visible (or otherwise in evidence)
        - label: Update RELEASE NOTES and transfer to OAR-developer repo

  - type: textarea
    id: failures
    attributes:
      label: Issues Found

  - type: dropdown
    id: result
    attributes:
      label: Overall Result
      options:
        - Pass
        - Pass with follow-ups
        - Fail
    validations:
      required: true
