name: "Acceptance - Datapubtest (Legacy)"
description: "Validate datapubtest.nist.gov"
title: "[Acceptance][Datapubtest] "
labels:
  - acceptance-testing
  - legacy
body:
  - type: markdown
    attributes:
      value: "PDR Publications (Legacy) - Datapubtest.nist.gov"

  - type: checkboxes
    id: legacy_checks
    attributes:
      label: Datapubtest Checklist
      options:
        - label: Create record and View on Landing Page
        - label: Edit Landing page Data
        - label: Test Data File Download (note sha file may not yet be accessible for download)

  - type: textarea
    id: failures
    attributes:
      label: Failures

  - type: dropdown
    id: result
    attributes:
      label: Result
      options:
        - Pass
        - Fail
