name: "Acceptance - Production MIDAS/PDR"
description: "Production validation for MIDAS/PDR"
title: "[Acceptance][Production MIDAS/PDR] "
labels:
  - production-validation
body:
  - type: markdown
    attributes:
      value: |
        For the production deployment of MIDAS/PDR the following acceptance test items will be performed to validate the performance and function of the system.

  - type: checkboxes
    id: prod_checks
    attributes:
      label: Production Checklist
      options:
        - label: Create a Test Record in MIDAS and Perform Editing in PDR Landing Page
        - label: Enter all required Metadata
        - label: Contacts Tab.  Select Edit Homepage (the PDR Landing Page) and create authors.
        - label: Return to MIDAS and complete metadata entry
        - label: Upload one or more Test Data Files in MIDAS,  Save File (need file in Published record for later Public dataset access validation)
        - label: Under MIDAS Access Tab,   Edit Landing Page
        - label: Validate PDR Editing Features work correctly.   Save Changes.  Select Finish.
        - label: MIDAS Accept Changes.
        - label: Validate Datacite DOI call functioned correctly (preservation service calls Datacite API and adds DOI into the metadata)
        - label: Modify Saved Record in MIDAS
        - label: Delete Data File in MIDAS
        - label: Repeat Edit Landing Page,  validate File was removed.
        - label: Complete Publish of Record (Fast track Review, Curate)
        - label: Try to Edit MIDAS record for unauthorized record (May require tester for restricted access to MIDAS)
        - label: Validate Published Record access in Public Data Repository
        - label: verify all metadata captured as expected
        - label: Verify DOI
        - label: Verify File Downloads
        - label: Verify all metadata was captured
        - label: Verify PDR page links
        - label: Verify Data Cart functionality

  - type: textarea
    id: failures
    attributes:
      label: Failures

  - type: dropdown
    id: result
    attributes:
      label: Result
      options:
        - Pass
        - Fail
